input:
  kafka:
    addresses: [ "redpanda:9092" ]
    # Debezium creates topics named: servername.schema.table
    topics: [ "dbserver1.public.users" ]
    consumer_group: "benthos_cleaner"

pipeline:
  processors:
    # 1. Map Debezium structure to your Clean structure
    - mapping: |
        root.op = this.op
        
        # Debezium sends 'c' for create, 'u' for update, 'd' for delete
        if this.op == "d" {
            root.id = this.before.id
        } else {
            root.id = this.after.id
            root.email = this.after.email
            root.full_name = this.after.full_name
        }
        
        # Remove null fields and extra metadata
        root = root.filter(v -> v != null)

output:
  kafka_franz:
    seed_brokers: [ "redpanda:9092" ]
    topic: "user-created-events" # <--- The topic your Java App listens to
    key: "${! this.id }"