input:
  kafka:
    addresses: [ "redpanda:9092" ]
    # Debezium will create this topic automatically (server.schema.table)
    topics: [ "dbserver1.public.users" ]
    consumer_group: "benthos_cleaner"

pipeline:
  processors:
    # 1. Map Debezium structure to your Service 2 structure
    - mapping: |
        root.op = this.op
        
        # 'd' = delete (use 'before' state)
        # 'c'/'u' = create/update (use 'after' state)
        if this.op == "d" {
            root.id = this.before.id
        } else {
            root.id = this.after.id
            root.email = this.after.email
            root.full_name = this.after.full_name
        }
        
        # Remove nulls (like 'before' during a create)
        root = root.filter(v -> v != null)

output:
  kafka_franz:
    seed_brokers: [ "redpanda:9092" ]
    topic: "user-created-events" # <--- Service 2 listens here
    key: "${! this.id }"