input:
  postgres_cdc:
    dsn: "postgres://postgres:postgres@postgres:5432/service_1?sslmode=disable"
    slot_name: "service_1_cdc_slot"
    schema: "public"
    tables: [ "users" ]
    stream_snapshot: true

pipeline:
  processors:
    # 1. LOGIC: Handle Delete vs. Create/Update
    - mapping: |
        root.op = this.op 
        if this.op == "d" {
            root.data = this.before
        } else {
            root.data = this.after
        }

    # 2. SECURITY: Flatten and remove password
    - mapping: |
        root.op = this.op
        root.id = this.data.id
        
        if root.op != "d" {
            root.email = this.data.email
            root.full_name = this.data.full_name
        }

output:
  kafka_franz:
    seed_brokers: [ "redpanda:9092" ]
    topic: "user-created-events"
    # FIXED LINE BELOW:
    key: "${! this.id }"